
# cargo-vet audits file

[audits]

[[trusted.displaydoc]]
criteria = "safe-to-deploy"
user-id = 1139 # Manish Goregaokar (Manishearth)
start = "2024-06-20"
end = "2027-07-28"

[[trusted.forensicnomicon]]
criteria = "safe-to-deploy"
user-id = 347968 # Albert Hui (h4x0r)
start = "2026-06-05"
end = "2027-08-07"

[[trusted.forensicnomicon-core]]
criteria = "safe-to-deploy"
user-id = 347968 # Albert Hui (h4x0r)
start = "2026-06-28"
end = "2027-08-07"

[[trusted.forensicnomicon-data]]
criteria = "safe-to-deploy"
user-id = 347968 # Albert Hui (h4x0r)
start = "2026-06-28"
end = "2027-08-07"

[[trusted.safe-read]]
criteria = "safe-to-deploy"
user-id = 347968 # Albert Hui (h4x0r)
start = "2026-07-15"
end = "2027-08-07"

[[trusted.syn]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-03-01"
end = "2027-08-27"
